name: My Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    
      - name: Run script
        run: |
          echo hello world
          touch test
          
