name: My Action

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run script
        run: |
          echo hello 
          touch test
          ls -l
          

          
