name: Simple CI Workflow

# Run the workflow on push to the main branch
on:
  push:
    branches:
      - main

# Define the jobs for the workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests (if applicable)
      - name: Run tests
        run: npm test

          
